apiVersion: v1
kind: Service
metadata:
  name: reddit-clone-service
  namespace: reddit-clone
  labels:
    app: reddit-clone-app 
spec:
  selector:
    app: reddit-clone-app
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
